FileVersion = 1

[Project]
Name = "wren-beef"
DefaultNamespace = "wren"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\wren_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\wren.lib"]
